name: Mirror AetrisVPN Configs

on:
  schedule:
    - cron: '*/15 * * * *'  # Каждый час в 0, 15, 30 и 45 минут
  workflow_dispatch:        # Кнопка для ручного запуска

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download configs from Google Drive
        run: |
          curl -L "https://drive.usercontent.google.com/download?id=1uTVZsfiqGGzV5sLTjcoaf2cotQSQPSBg&export=download&confirm=t" -o AetrisVPN.txt

      - name: Commit and push if changed
        run: |
          git config user.name "CatlerBot"
          git config user.email "catler@gitverse.ru"
          git add AetrisVPN.txt
          (git diff --quiet && git diff --staged --quiet) || (git commit -m "Автообновление подписки" && git pull --rebase origin master && git push origin master)
